# Generated by Django 4.0.6 on 2022-08-08 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0003_alter_shorturl_original_url_alter_shorturl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(unique=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
